language: python
python:
  - 3.9

services:
  - docker

before_install:
  - docker build -f Dockerfile -t calculator2.

install:
  - pip install -r requirements.txt

script:
  - python runTestProcess.py

branches:
  only:
    - master