language: python
python:
  - 3.7

services:
  - docker

before_install:
  - docker build -f Dockerfile -t python-stats-calc .

install:
  - pip install -r requirements.txt
# command to run tests

script:
  - python runTestProcess.py

branches:
  only:
    - master