language: python
python:
  - 3.9

services:
  - docker

before_install:
  - docker build -f Dockerfile -t python-stats-calc .

install:
  - pip script -r requirements.txt

script:
  - python runTestProcess.py

branches:
  only:
    - main