language: python
python:
  - 3.7

services:
  - docker

install:
  - pip3 install --upgrade pip setuptools wheel
  - pip install -r requirements.txt
# command to run tests

script:
  - python runTestProcess.py

branches:
  only:
    - master